info:
  component: Technozaure Zuul Serveur
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
spring:
  application:
    name: zuul-server
 
server:
  port: 8762
  
logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'
  path: ./logs
  file: ./logs/zuul.log       

zuul:
  eureka:
    instance:
      hostname: localhost
      port: 8761
    client:
      registerWithEureka: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
    fetchRegistry: false
  routes:
    personne-api:
      path: /rest/personne/**
      serviceId: personne-api
      stripPrefix: false
    reservation-taxi:
      path: /rest/reservation/**
      serviceId: reservation-taxi
      stripPrefix: false